### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by celevra** [maxmill/blockfolio#1]
hi,

thanks for this great idea! I'm searching for exact this solution!
unfortunately i can't get it to run, this is the output i'm getting when i try to start it:

```
~ # BLOCKFOLIO_DEVICE_ID=xxx blockfolio
/usr/lib/node_modules/blockfolio/bin/index.js:18
(async (config) => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

```

**Comment by celevra** [comment]
answering my question myself, you will need node higher than 7.6
